In [1]:
import numpy as np
np.set_printoptions(suppress=True, linewidth=100, precision=2)

# Importing data

In [2]:
raw_data = np.genfromtxt('loan-data.csv', delimiter=';', encoding='unicode_escape', skip_header=1)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [3]:
raw_data.shape

(10000, 14)

# Missing data

In [4]:
x = np.isnan(raw_data).sum(axis=0)
for n in x:
    print(n, end=', ')

0, 10000, 500, 10000, 500, 10000, 6004, 501, 10000, 10000, 10000, 10000, 10000, 500, 

In [5]:
x

array([    0, 10000,   500, 10000,   500, 10000,  6004,   501, 10000, 10000, 10000, 10000, 10000,
         500])

In [6]:
tmp_fill = np.nanmax(raw_data) +1
tmp_mean = np.nanmean(raw_data, axis=0)

<ipython-input-6-87d3f22b7e10>:2: RuntimeWarning: Mean of empty slice
  tmp_mean = np.nanmean(raw_data, axis=0)


In [7]:
tmp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [8]:
tmp_stas = np.array([
    np.nanmin(raw_data, axis=0),
    np.nanmean(raw_data, axis=0),
    np.nanmax(raw_data, axis=0)
])

<ipython-input-8-94cb668fbb28>:2: RuntimeWarning: All-NaN slice encountered
  np.nanmin(raw_data, axis=0),
<ipython-input-8-94cb668fbb28>:3: RuntimeWarning: Mean of empty slice
  np.nanmean(raw_data, axis=0),
<ipython-input-8-94cb668fbb28>:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis=0)


In [9]:
tmp_stas

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# Splitting data

In [10]:
column_strings = np.argwhere(np.isnan(tmp_mean))
column_strings

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

In [11]:
column_strings.squeeze(), column_strings.ravel(), column_strings.flatten()

(array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64),
 array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64),
 array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64))

In [12]:
column_strings= column_strings.squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [13]:
column_numeric = np.argwhere(~np.isnan(tmp_mean)).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# reimporting data

In [14]:
data_strings = np.genfromtxt('loan-data.csv', delimiter=';', skip_header=True, autostrip=True, encoding='unicode_escape',
                           usecols=column_strings, dtype=np.str_)

data_strings


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [15]:
data_numeric = np.genfromtxt('loan-data.csv', delimiter=';', skip_header=True, autostrip=True, encoding='unicode_escape',
                           usecols=column_numeric, filling_values=tmp_fill)

data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [16]:
raw_data.shape[0]

10000

In [17]:
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

# Column names

In [16]:
header_full = np.genfromtxt('loan-data.csv', delimiter=';', skip_footer=raw_data.shape[0], autostrip=True, encoding='unicode_escape',
                           dtype=np.str_)

header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [17]:
header_strings, header_numeric = header_full[column_strings], header_full[column_numeric]
print(header_strings)
print(header_numeric)

['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']
['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


# Create checkpoints

In [18]:
def checkpoint(filename, checkpoint_header, chekpoint_data):
    np.savez(filename, header=checkpoint_header, data=chekpoint_data)
    checkpoint_variable = np.load(filename+".npz")
    return checkpoint_variable

In [19]:
checkpoint_test = checkpoint("checkpoint-test", header_strings, data_strings)

In [22]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [23]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

# Manipulating String columns

In [24]:
header_strings[0] = "issue_date"
data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

## Issue Date

In [25]:
data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [26]:
np.unique(data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [30]:
data_strings[:,0] = np.chararray.strip(data_strings[:,0], "-15")

In [32]:
months = np.array(["", 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [33]:
for i in range(len(months)):
    data_strings[:,0] = np.where(data_strings[:,0] == months[i], i, data_strings[:,0])

In [34]:
data_strings[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

## Loan Status

In [35]:
data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [37]:
np.unique(data_strings[:,1]), np.unique(data_strings[:,1]).size

(array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
        'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69'),
 9)

In [38]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])
status_good = np.array(['Current', 'Fully Paid', 'In Grace Period', 'Late (16-30 days)', 'Issued'])

In [41]:
data_strings[:,1] = np.where(np.isin(data_strings[:,1], status_bad), 0,1)


array([['5', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [42]:
data_strings[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

## Term

In [43]:
data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [44]:
np.unique(data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [45]:
data_strings[:,2] = np.chararray.strip(data_strings[:,2], ' months')
np.unique(data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [46]:
header_strings[2] = "term_months"
data_strings[:,2] = np.where(data_strings[:,2]=='', '60', data_strings[:,2])
np.unique(data_strings[:,2])

array(['36', '60'], dtype='<U69')

## Grade and Subgrade

In [47]:
data_strings[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [48]:
np.unique(data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [49]:
print(data_strings[:,4])

print(np.unique(data_strings[:,4]))


['C3' 'A5' 'B5' ... 'A5' 'D2' 'A4']
['' 'A1' 'A2' 'A3' 'A4' 'A5' 'B1' 'B2' 'B3' 'B4' 'B5' 'C1' 'C2' 'C3' 'C4' 'C5' 'D1' 'D2' 'D3' 'D4'
 'D5' 'E1' 'E2' 'E3' 'E4' 'E5' 'F1' 'F2' 'F3' 'F4' 'F5' 'G1' 'G2' 'G3' 'G4' 'G5']


In [55]:
for g in np.unique(data_strings[:,3])[1:]:
    data_strings[:,4] = np.where(((data_strings[:, 4] == '') & (data_strings[:,3] == g)), 
                                 g+'5', data_strings[:,4])


In [62]:
print(np.unique(data_strings[:,4], return_counts=True))


(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'), array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
       250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))


In [63]:
data_strings[:,4] = np.where(data_strings[:, 4] == '', 'H1', data_strings[:,4])

In [65]:
print(np.unique(data_strings[:,4]))

['A1' 'A2' 'A3' 'A4' 'A5' 'B1' 'B2' 'B3' 'B4' 'B5' 'C1' 'C2' 'C3' 'C4' 'C5' 'D1' 'D2' 'D3' 'D4'
 'D5' 'E1' 'E2' 'E3' 'E4' 'E5' 'F1' 'F2' 'F3' 'F4' 'F5' 'G1' 'G2' 'G3' 'G4' 'G5' 'H1']


In [61]:
((data_strings[:, 4] == '') & (data_strings[:,3] == g)).sum()

0

In [66]:
data_strings = np.delete(data_strings,3, axis=1)

In [67]:
data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [69]:
header_strings = np.delete(header_strings, 3)
header_strings[3]

'sub_grade'

In [71]:
keys = np.unique(data_strings[:,3])
values = range(1, keys.shape[0]+1)
dict_sub_grade = dict(zip(keys,values))
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [72]:
for g in keys:
    data_strings[:,3] = np.where(data_strings[:,3]==g, dict_sub_grade.get(g), data_strings[:,3])

## Verification status

In [73]:
data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [74]:
np.unique(data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [75]:
data_strings[:,4] = np.where((data_strings[:,4]=='') | (data_strings[:,4]=='Not Verified'), 0, 1)
np.unique(data_strings[:,4])

array(['0', '1'], dtype='<U69')

## URL

In [76]:
print(data_strings[:,5])

print(np.unique(data_strings[:,5]))

['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726' ...
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249']
['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426' ...
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572'
 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994']


In [77]:
np.chararray.strip(data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [78]:
np.unique(np.chararray.strip(data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id='))

chararray(['12606806', '13026045', '1312426', ..., '8138291', '8214572', '849994'], dtype='<U69')

In [79]:
data_strings[:,5] = np.chararray.strip(data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [82]:
data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [83]:
np.array_equal(data_numeric[:,0].astype(np.int32), data_strings[:,5].astype(np.int32))

True

In [84]:
data_strings = np.delete(data_strings,5, axis=1)
header_strings = np.delete(header_strings, 5)

## State Address

In [85]:
header_strings[5] = 'state_address'

In [86]:
print(data_strings[:,5])

print(np.unique(data_strings[:,5]))

['CA' 'NY' 'PA' ... 'CA' 'OH' 'IL']
['' 'AK' 'AL' 'AR' 'AZ' 'CA' 'CO' 'CT' 'DC' 'DE' 'FL' 'GA' 'HI' 'IL' 'IN' 'KS' 'KY' 'LA' 'MA' 'MD'
 'ME' 'MI' 'MN' 'MO' 'MS' 'MT' 'NC' 'ND' 'NE' 'NH' 'NJ' 'NM' 'NV' 'NY' 'OH' 'OK' 'OR' 'PA' 'RI'
 'SC' 'SD' 'TN' 'TX' 'UT' 'VA' 'VT' 'WA' 'WI' 'WV' 'WY']


In [88]:
states_names, states_count = np.unique(data_strings[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [91]:
data_strings[:,5] = np.where(data_strings[:,5] == '', 
                                  0, 
                                  data_strings[:,5])

In [92]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [93]:
data_strings[:,5] = np.where(np.isin(data_strings[:,5], states_west), 1, data_strings[:,5])
data_strings[:,5] = np.where(np.isin(data_strings[:,5], states_south), 2, data_strings[:,5])
data_strings[:,5] = np.where(np.isin(data_strings[:,5], states_midwest), 3, data_strings[:,5])
data_strings[:,5] = np.where(np.isin(data_strings[:,5], states_east), 4, data_strings[:,5])

In [94]:
np.unique(data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [95]:
data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [97]:
data_strings = data_strings.astype(np.int32)

In [98]:
data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

### Checkpoint 1: Strings

In [99]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_strings, data_strings)

In [100]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [101]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], dtype=int32)

In [102]:
np.array_equal(checkpoint_strings['data'], data_strings)

True

# Manipulating Numeric Columns